### ISSUE TITLE
What about event versioning/serialization

### ISSUE THREAD

**Issue by dsebastien** [pilloPl/event-source-cqrs-sample#9]
Hello,

Interesting repositories!

I've spent quite some time earlier this year looking into EDA and ES. One area in which I think there's quite a lot of complexity to think about is around how to handle the versioning of events.

For example in this repository, I see that you are serializing events to JSON, but don't seem to have schemas. To me, it feels like Avro and Protobuf are sort of must-haves in order to actually be able to manage both versioning and "safe" collaboration where distributed systems can handle events.

In my PoCs, I actually persisted Avro-serialized objects into my database, along with their schemas (also versioned). I can't really comment about the performances (didn't benchmark the solution), but it felt much safer to me to actually have versioning right from the start, simply assuming that requirements do evolve and that events may evolve, appear/disappear over time.

What's your take on this? How do you handle event versioning & serialization?

**Comment by pilloPl** [comment]
Hello!

Thanks for your insight. 

I completely agree with your points. These repository is a sample that aims to show that event sourcing and cqrs are not that fancy patterns. Naturally, when you go to production, versioning is a must.

In my experience, backward and forward compatibility and layer of translation that maps v1 to v2 is a good start. Then Avro. :)

PS: take a Look at this: https://leanpub.com/esversioning

Thanks one more time.
